# Generated by Django 4.1.3 on 2022-11-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("porfolio", "0002_alter_project_options_project_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="url",
            new_name="link",
        ),
    ]
